### ISSUE TITLE
Support the new `esprima` option

### ISSUE THREAD

**Issue by mikesherov** [jscs-dev/gulp-jscs#56]
This would allow people to use esprima-fb and have JSCS run on their jsx files.

**Comment by niba** [comment]
There is possibility to turn on esprima-fb.
Try this:
`.pipe(jscs({
            esprima: 'esprima-fb'
        }));`

**Comment by joemaller** [comment]
The option @niba mentioned works correctly. One note for those googling their way here looking for ways to use JSCS and React's JSX in gulp: Explicitly passing options to jscs in a gulp pipeline seems to override options from your `.jscsrc` file. If you're using a `.jscsrc` file, add the `"esprima": "esprima-fb"` key there. You will also need to have esprima-fb installed. 

@mikesherov How does this not solve your issue? With `esprima-fb` gulp-jscs appears to work perfectly with a mixed js/jsx workflow. If you wanted a strict separation between jsx and js files, wouldn't multiple pipes be a better solution?

To me, this issue seems resolved and could be closed.

**Comment by sindresorhus** [comment]
The `esprima` option can now be passed in your JSCS config instead: http://jscs.info/overview#esprima
