### ISSUE TITLE
Don't fail task

### ISSUE THREAD

**Issue by stevemao** [jscs-dev/gulp-jscs#84]
I kinda like this option in gulp-jshint https://github.com/spalger/gulp-jshint#fail-reporter So the task doesn't have to fail if not specified. Is it standard for gulp? Do you think it's a good idea to implement it here?

I usually combine gulp-jshint and gulp-jscs in my projects but the settings look completely inconsistent (I expect them to have similar apis).

**Comment by sindresorhus** [comment]
Yeah, this depends on #66.

**Comment by anilnatha** [comment]
So I've been learning gulp, and started out by making out a simple script to help improve my development workflow. As you can see in the code I'm using the gulp plugin `run-sequence` to force that each task run consecutively, rather than concurrently. I think the issue I have come across is along the lines of the feature that stevemao has requested.

Listed below is code that works, but let me explain the issue I came across. My watch task has a runSequence call has three tasks specified. Without the `.on('error',handleJscsError);` call in the jscs task, any tasks specified _after_ the jscs task in the runSequence are never called with the exception of the callback specified at the end of the runSequence parameter list. It would nice if jscs worked much like jshint where if issues are found with watched files, it doesn't break any subsequence calls. However, even without the `jshint.reporter('fail')` specified for jshint, if jshint finds an issue to report, it doesn't break any subsequent calls. So although I do wish we had an option to do something like `jscs.reporter('fail')`, even without it, a simple call to `jscs` shouldn't break.

	/* File: gulpfile.js */

	/* grab the packages we will be using */
	var gulp = require('gulp');
	var gUtil = require('gulp-util');
	var jscs = require('gulp-jscs');
	var jsHint = require('gulp-jshint');
	var jsHintStylish = require('jshint-stylish');
	var runSequence = require('run-sequence');
	var console = require('better-console');

	// default error handler
	var handleJscsError = function(err) {
	 	console.log("Error: " + err.toString());
	 	this.emit('end');
	}

	// configure the default task and add the watch task to it
	gulp.task('default', ['watch']);

	// configure the jscs task
	gulp.task('jscs', function() {
		return gulp.src('src/app/**/*.js')
			.pipe(jscs('.jscsrc'))
			.on('error',handleJscsError);
	});

	// configure the lint task
	gulp.task('lint', function() {
		return gulp.src("src/app/**/*.js")
			.pipe(jsHint('.jshintrc'))
			.pipe(jsHint.reporter(jsHintStylish));
	});

	gulp.task('build', function() {

	})

	// configure the watch task - set up which files to watch and what tasks to use when those files change
	gulp.task('watch', function() {

		// Clear console
		console.clear();

		// setup a watch against the files that need to be checked on save
		return gulp.watch('src/app/**/*.js', function(){

			// Clear console so only current issues are shown
			console.clear();
			
			// Execute tasks to check code for issues
			runSequence('jscs','lint','build',function(){
				console.log("Tasks Completed.")
			});

		});

	});

My apologies if what I have stated is unclear or require further explanation. I'm new to gulp and want to do my best to help you guys out in improving this useful tool. Cheers.

**Comment by hbrysiewicz** [comment]
+1 thank you for the solution but I agree that gulp-jscs should behave more like jshint and not break subsequent tasks on failure by default

**Comment by sindresorhus** [comment]
[Fixed in 3.0.0](https://github.com/jscs-dev/gulp-jscs/releases/tag/v3.0.0)

**Comment by dryoma** [comment]
Sorry for bringing this up.

I'm trying to make `gulp-jscs` run on file changes, and if - an error is encountered - just report it, without breaking watch *and* without continuing the stream (e.g., a file with errors doesn't get uglified and doesn't go to a dest folder). With no success yet.

gulpfile looks like this:
```
var gulp = require('gulp'),
	jscs = require('gulp-jscs'),
	uglify = require('gulp-uglify');

gulp.task('js', function(){
	gulp.src('js/*.js')
		.pipe(jscs())
		.pipe(jscs.reporter())
		.pipe(jscs.reporter('failImmediately')).on('error', function(e){
			this.emit('end');
			this.end();
		})
		.pipe(uglify()) // This should not fire if jscs finds an error. But it does.
		.pipe(gulp.dest('dist/js/'));
});

gulp.task('default', function(){
	gulp.watch('js/*.js', ['js'])
});
```

**Comment by dryoma** [comment]
Sorry for bringing this up.

I'm trying to make `gulp-jscs` run on file changes, and - if an error is encountered - just report it, without breaking watch **and** without continuing the stream (e.g., a file with errors doesn't get uglified and doesn't go to a dest folder). And can't seem to succeed in both with gulp-jscs: either the `fail` (or `failImmediage`) reporter breaks a watch, or, if I catch stream errors, the stream doesn't stop.

I should note that if the error handler is attached after the call to, for example, `gulp-uglify`, it works as it should: there is no throw and the stream doesn't continue.

Am I right to assume that it's `gulp-jscs` that is unable to do what I need it to do? And if so, is there a way to fix this?

gulp v3.9.0, gulp-jscs v3.0.2, the gulpfile looks like this:
```
var gulp = require('gulp'),
    jscs = require('gulp-jscs'),
    uglify = require('gulp-uglify');

gulp.task('js', function(){
    gulp.src('js/*.js')
        .pipe(jscs())
        .pipe(jscs.reporter())
        .pipe(jscs.reporter('failImmediately'))
        .on('error', function(e){
            this.emit('end');
        })
        .pipe(uglify()) // This should not fire if jscs finds an error. But it does.
        .pipe(gulp.dest('dist/js/'));
});

gulp.task('default', function(){
    gulp.watch('js/*.js', ['js'])
});
```
